#ifndef CURRENCIES_H
#define CURRENCIES_H

#include "types.h"

struct Currencies
{
    static const String AED; // "United Arab Emirates Dirham",
    static const String AFN; // "Afghan Afghani",
    static const String ALL; // "Albanian Lek",
    static const String AMD; // "Armenian Dram",
    static const String ANG; // "Netherlands Antillean Guilder",
    static const String AOA; // "Angolan Kwanza",
    static const String ARS; // "Argentine Peso",
    static const String AUD; // "Australian Dollar",
    static const String AWG; // "Aruban Florin",
    static const String AZN; // "Azerbaijani Manat",
    static const String BAM; // "Bosnia-Herzegovina Convertible Mark",
    static const String BBD; // "Barbadian Dollar",
    static const String BDT; // "Bangladeshi Taka",
    static const String BGN; // "Bulgarian Lev",
    static const String BHD; // "Bahraini Dinar",
    static const String BIF; // "Burundian Franc",
    static const String BMD; // "Bermudan Dollar",
    static const String BND; // "Brunei Dollar",
    static const String BOB; // "Bolivian Boliviano",
    static const String BRL; // "Brazilian Real",
    static const String BSD; // "Bahamian Dollar",
    static const String BTC; // Bitcoin
    static const String BTN; // "Bhutanese Ngultrum",
    static const String BWP; // "Botswanan Pula",
    static const String BYR; // "Belarusian Ruble",
    static const String BZD; // "Belize Dollar",
    static const String CAD; // "Canadian Dollar",
    static const String CDF; // "Congolese Franc",
    static const String CHF; // "Swiss Franc",
    static const String CLF; // "Chilean Unit of Account (UF)",
    static const String CLP; // "Chilean Peso",
    static const String CNC; // "Chinacoin",
    static const String CNY; // "Chinese Yuan",
    static const String COP; // "Colombian Peso",
    static const String CRC; // "Costa Rican Colón",
    static const String CUP; // "Cuban Peso",
    static const String CVE; // "Cape Verdean Escudo",
    static const String CZK; // "Czech Republic Koruna",
    static const String DJF; // "Djiboutian Franc",
    static const String DKK; // "Danish Krone",
    static const String DOP; // "Dominican Peso",
    static const String DVC; // Devcoin,
    static const String XDC; // Dogecoin,
    static const String DZD; // "Algerian Dinar",
    static const String EEK; // "Estonian Kroon",
    static const String EGP; // "Egyptian Pound",
    static const String ETB; // "Ethiopian Birr",
    static const String EUR; // "Euro",
    static const String FJD; // "Fijian Dollar",
    static const String FKP; // "Falkland Islands Pound",
    static const String FTC; // "Feathercoin",
    static const String GBP; // "British Pound Sterling",
    static const String GEL; // "Georgian Lari",
    static const String GHS; // "Ghanaian Cedi",
    static const String GHs; // "Gigahashes per second",
    static const String GIP; // "Gibraltar Pound",
    static const String GMD; // "Gambian Dalasi",
    static const String GNF; // "Guinean Franc",
    static const String GTQ; // "Guatemalan Quetzal",
    static const String GYD; // "Guyanaese Dollar",
    static const String HKD; // "Hong Kong Dollar",
    static const String HNL; // "Honduran Lempira",
    static const String HRK; // "Croatian Kuna",
    static const String HTG; // "Haitian Gourde",
    static const String HUF; // "Hungarian Forint",
    static const String IDR; // "Indonesian Rupiah",
    static const String ILS; // "Israeli New Sheqel",
    static const String INR; // "Indian Rupee",
    static const String IQD; // "Iraqi Dinar",
    static const String IRR; // "Iranian Rial",
    static const String ISK; // "Icelandic Króna",
    static const String IXC; // iXcoin,
    static const String JEP; // "Jersey Pound",
    static const String JMD; // "Jamaican Dollar",
    static const String JOD; // "Jordanian Dinar",
    static const String JPY; // "Japanese Yen",
    static const String KES; // "Kenyan Shilling",
    static const String KGS; // "Kyrgystani Som",
    static const String KHR; // "Cambodian Riel",
    static const String KMF; // "Comorian Franc",
    static const String KPW; // "North Korean Won",
    static const String KRW; // "South Korean Won",
    static const String KWD; // "Kuwaiti Dinar",
    static const String KYD; // "Cayman Islands Dollar",
    static const String KZT; // "Kazakhstani Tenge",
    static const String LAK; // "Laotian Kip",
    static const String LBP; // "Lebanese Pound",
    static const String LKR; // "Sri Lankan Rupee",
    static const String LRD; // "Liberian Dollar",
    static const String LSL; // "Lesotho Loti",
    static const String LTC; // "Litecoin",
    static const String LTL; // "Lithuanian Litas",
    static const String LVL; // "Latvian Lats",
    static const String LYD; // "Libyan Dinar",
    static const String MAD; // "Moroccan Dirham",
    static const String MDL; // "Moldovan Leu",
    static const String MGA; // "Malagasy Ariary",
    static const String MKD; // "Macedonian Denar",
    static const String MMK; // "Myanma Kyat",
    static const String MNT; // "Mongolian Tugrik",
    static const String MOP; // "Macanese Pataca",
    static const String MRO; // "Mauritanian Ouguiya",
    static const String MUR; // "Mauritian Rupee",
    static const String MVR; // "Maldivian Rufiyaa",
    static const String MWK; // "Malawian Kwacha",
    static const String MXN; // "Mexican Peso",
    static const String MYR; // "Malaysian Ringgit",
    static const String MZN; // "Mozambican Metical",
    static const String NAD; // "Namibian Dollar",
    static const String NGN; // "Nigerian Naira",
    static const String NIO; // "Nicaraguan Córdoba",
    static const String NMC; // Namecoin,
    static const String NOK; // "Norwegian Krone",
    static const String NPR; // "Nepalese Rupee",
    static const String NVC; // "Novacoin",
    static const String NZD; // "New Zealand Dollar",
    static const String OMR; // "Omani Rial",
    static const String PAB; // "Panamanian Balboa",
    static const String PEN; // "Peruvian Nuevo Sol",
    static const String PGK; // "Papua New Guinean Kina",
    static const String PHP; // "Philippine Peso",
    static const String PKR; // "Pakistani Rupee",
    static const String PLN; // "Polish Zloty",
    static const String PPC; // "Peercoin",
    static const String PYG; // "Paraguayan Guarani",
    static const String QAR; // "Qatari Rial",
    static const String RON; // "Romanian Leu",
    static const String RSD; // "Serbian Dinar",
    static const String RUB; // "Russian Ruble",
    static const String RUR; // "Old Russian Ruble",
    static const String RWF; // "Rwandan Franc",
    static const String SAR; // "Saudi Riyal",
    static const String SBD; // "Solomon Islands Dollar",
    static const String SCR; // "Seychellois Rupee",
    static const String SDG; // "Sudanese Pound",
    static const String SEK; // "Swedish Krona",
    static const String SGD; // "Singapore Dollar",
    static const String SHP; // "Saint Helena Pound",
    static const String SLL; // "Sierra Leonean Leone",
    static const String SOS; // "Somali Shilling",
    static const String SRD; // "Surinamese Dollar",
    static const String STD; // "São Tomé and Príncipe Dobra",
    static const String SVC; // "Salvadoran Colón",
    static const String SYP; // "Syrian Pound",
    static const String SZL; // "Swazi Lilangeni",
    static const String THB; // "Thai Baht",
    static const String TJS; // "Tajikistani Somoni",
    static const String TMT; // "Turkmenistani Manat",
    static const String TND; // "Tunisian Dinar",
    static const String TOP; // "Tongan Paʻanga",
    static const String TRC; // "Terracoin",
    static const String TRY; // "Turkish Lira",
    static const String TTD; // "Trinidad and Tobago Dollar",
    static const String TWD; // "New Taiwan Dollar",
    static const String TZS; // "Tanzanian Shilling",
    static const String UAH; // "Ukrainian Hryvnia",
    static const String UGX; // "Ugandan Shilling",
    static const String USD; // "United States Dollar",
    static const String UYU; // "Uruguayan Peso",
    static const String UZS; // "Uzbekistan Som",
    static const String VEF; // "Venezuelan Bolívar",
    static const String VEN; // Hub Culture's Ven,
    static const String VND; // "Vietnamese Dong",
    static const String VUV; // "Vanuatu Vatu",
    static const String WDC; // "WorldCoin",
    static const String WST; // "Samoan Tala",
    static const String XAF; // "CFA Franc BEAC",
    static const String XBT; // Bitcoin,
    static const String XCD; // "East Caribbean Dollar",
    static const String XDR; // "Special Drawing Rights",
    static const String XOF; // "CFA Franc BCEAO",
    static const String XPF; // "CFP Franc",
    static const String XPM; // "Primecoin",
    static const String XRP; // Ripple
    static const String XVN; // Hub Culture's Ven,
    static const String YER; // "Yemeni Rial",
    static const String ZAR; // "South African Rand",
    static const String ZMK; // "Zambian Kwacha",
    static const String ZWL; // "Zimbabwean Dollar"

};

#endif // CURRENCIES_H
